#!/usr/bin/env python3

import os
import sys
import pandas as pd
from pathlib import Path

##################################
# Based on gene count tables generated in step 1, this script merges per-SRR gene-count tables into three matrices:
#   (1) spliced matrix
#   (2) unspliced matrix
#   (3) ambiguous matrix
# Each matrix has genes as rows and SRR samples/cells as columns.
##################################

print("-- Step 2: construct gene-count tables for the three groups --")

# Get the location of this script.
script_dir = Path(__file__).resolve().parent
# Back to the root of the project.
project_root = (script_dir / "../../").resolve()

# Optional input parameters
#   $1 = gene count file directory
#   $2 = output directory
gene_count_root = Path(
    sys.argv[1] if len(sys.argv) > 1
    else project_root / "results/scvelo/1_gene_counts"
).resolve()

outdir = Path(
    sys.argv[2] if len(sys.argv) > 2
    else project_root / "results/scvelo/2_matrices"
).resolve()

outdir.mkdir(parents=True, exist_ok=True)

# Set output files
output_files = {
    "spliced": outdir / "method_spliced_matrix.tsv",
    "unspliced": outdir / "method_unspliced_matrix.tsv",
    "ambiguous": outdir / "method_ambiguous_matrix.tsv",
}

# Filename generated by the featureCounts script.
suffixes = {
    "spliced": "method_spliced_gene_counts.tsv",
    "unspliced": "method_unspliced_gene_counts.tsv",
    "ambiguous": "method_ambiguous_gene_counts.tsv",
}


# check input directory
if not gene_count_root.is_dir():
    raise FileNotFoundError(f"Gene count root directory not found: {gene_count_root}")

# Loop through SRR directories
cells = sorted(
    p.name for p in gene_count_root.iterdir()
    if p.is_dir() and p.name.startswith("SRR")
)

if len(cells) == 0:
    raise RuntimeError(f"No SRR sample directories found under {gene_count_root}")

print(f"Found {len(cells)} SRR samples: {gene_count_root}")

# Construct the build_matrix function
# It can reads the gene_id and count table, sums gene_id rows, then merge all samples into one matrix
def build_matrix(count_type):

    dfs = []
    missing_cells = []

    for cell in cells:
        path = gene_count_root / cell / f"{cell}_{suffixes[count_type]}"

        if not path.is_file():
            missing_cells.append(cell)
            continue

        df = pd.read_csv(
            path,
            sep="\t",
            header=None,
            names=["gene_id", cell]
        )

        # If a gene appears more than once, sum its counts.
        df = df.groupby("gene_id", as_index=False)[cell].sum()

        dfs.append(df)

    if len(dfs) == 0:
        raise RuntimeError(f"No valid files found for {count_type}")

    # Merge all the count tables based on gene_id
    merged = dfs[0]
    for df in dfs[1:]:
        merged = merged.merge(df, on="gene_id", how="outer")

    # fill missing gene counts with zero
    merged = merged.fillna(0)

    # convert the value in count columns to integers
    for col in merged.columns[1:]:
        merged[col] = merged[col].astype(int)

    # sort genes
    merged = merged.sort_values("gene_id")

    # add zero columns for SRR samples missing this count type
    for cell in cells:
        if cell not in merged.columns:
            merged[cell] = 0

    # keep the order of the columns with the SRR samples
    merged = merged[["gene_id"] + cells]

    return merged, missing_cells

# Build the three matrices
summary_lines = []

for count_type in ["spliced", "unspliced", "ambiguous"]:
    print(f"Building {count_type} matrix...")

    matrix, missing_cells = build_matrix(count_type)

    matrix.to_csv(
        output_files[count_type],
        sep="\t",
        index=False
    )

    summary_lines.append(f"{count_type}:")
    summary_lines.append(f"  output = {output_files[count_type]}")
    summary_lines.append(f"  genes  = {matrix.shape[0]}")
    summary_lines.append(f"  cells  = {matrix.shape[1] - 1}")

    if missing_cells:
        summary_lines.append(f"  missing_cells = {', '.join(missing_cells)}")
    else:
        summary_lines.append("  missing_cells = none")

    summary_lines.append("")


# Write the merge summary file with genes and cells counts for the three classifications.
summary_file = outdir / "merge_summary.txt"

with open(summary_file, "w") as f:
    f.write("\n".join(summary_lines))

print("All matrices written:")
for k, v in output_files.items():
    print(f"  {k}: {v}")

print(f"Summary written to: {summary_file}")