#!/bin/bash
#SBATCH --job-name=fc_method_cells
#SBATCH --partition=cpu6348
#SBATCH --qos=8cores
#SBATCH -n 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --output=%j.out
#SBATCH --error=%j.err

set -euo pipefail

module load subread
module load samtools/1.16.1-gcc-8.5.0-teyetiz

##################################
# This script runs featureCounts on three BAM files (mature, precursor, ambiguous) per cell generated by the method, and creates gene-count tables for downstream matrix construction
##################################

# Get the location of the script
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Back to the root of the project
project_root="$(cd "${script_dir}/../../" && pwd)"

# set gtf, inputs and outputs directories
gtf="${1:-${project_root}/data/short_read/references/mm39.gtf}"
method_root="${2:-${project_root}/results/short_read/5_final_results}"
outroot="${3:-${project_root}/results/scvelo/1_gene_counts}"

mkdir -p "${outroot}"

overall_log="${outroot}/batch_featureCounts_method_summary.log"
threads="${SLURM_CPUS_PER_TASK:-8}"

# add the output information to the overall log file
echo "-- Step 1: process featureCounts for method bam files --"
echo "GTF: ${gtf}" | tee -a "${overall_log}"
echo "Method_root: ${method_root}" | tee -a "${overall_log}"
echo "Output_root: ${outroot}" | tee -a "${overall_log}"

if [[ ! -f "${gtf}" ]]; then
    echo "Error: GTF not found: ${gtf}" | tee -a "${overall_log}"
    exit 1
fi

if [[ ! -d "${method_root}" ]]; then
    echo "Error: input method bam directory not found: ${method_root}" | tee -a "${overall_log}"
    exit 1
fi

# run featureCounts on one BAM file
run_fc() {
    local bam="$1"
    local outdir="$2"
    local prefix="$3"
    local log="$4"

    local raw_out="${outdir}/${prefix}_featureCounts.txt"
    local simple_out="${outdir}/${prefix}_gene_counts.tsv"
    local summary_out="${outdir}/${prefix}_featureCounts.summary"

    # Check whether the bam file exists, if not, add the output information to the single sample log file
    if [[ ! -f "${bam}" ]]; then
        echo "Error: bam file not found: ${bam}" | tee -a "${log}"
        exit 1
    fi
    
    # skip the sample if the count table already exists
    if [[ -f "${simple_out}" ]]; then
        echo "Skip existing file: ${simple_out}" | tee -a "${log}"
        return
    fi

    echo "Running featureCounts on: ${bam}" | tee -a "${log}"

    # validate the bam files
    samtools quickcheck "${bam}"
    echo "samtools quickcheck passed: ${bam}" | tee -a "${log}"

    # main function to extract a two column gene count table with exon counting and gene_id grouping
    featureCounts \
        -T "${threads}" \
        -a "${gtf}" \
        -o "${raw_out}" \
        -t exon \
        -g gene_id \
        "${bam}" \
        2>&1 | tee -a "${log}"

    if [[ ! -f "${raw_out}" ]]; then
        echo "Error: featureCounts output missing: ${raw_out}" | tee -a "${log}"
        exit 1
    fi

    if [[ -f "${raw_out}.summary" ]]; then
        mv "${raw_out}.summary" "${summary_out}"
    fi

    awk 'BEGIN{OFS="\t"} !/^#/ && NR>2 {print $1,$7}' "${raw_out}" > "${simple_out}"

    echo "Generated:" | tee -a "${log}"
    echo "  raw:     ${raw_out}" | tee -a "${log}"
    echo "  summary: ${summary_out}" | tee -a "${log}"
    echo "  simple:  ${simple_out}" | tee -a "${log}"
}

# Loop through SRR directories and process three BAM types
mapfile -t method_dirs < <(find "${method_root}" -mindepth 1 -maxdepth 1 -type d -name "SRR*" | sort)

if [[ "${#method_dirs[@]}" -eq 0 ]]; then
    echo "Error: no SRR sample found under ${method_root}" | tee -a "${overall_log}"
    exit 1
fi

echo "Found ${#method_dirs[@]} SRR samples." | tee -a "${overall_log}"

for method_dir in "${method_dirs[@]}"; do
    cell="$(basename "${method_dir}")"

    outdir="${outroot}/${cell}"
    mkdir -p "${outdir}"

    log="${outdir}/${cell}_featureCounts_summary.log"

    echo "featureCounts for ${cell}" | tee -a "${log}"
    echo "Start time: $(date)" | tee -a "${log}"
    echo "GTF file: ${gtf}" | tee -a "${log}"
    echo "Method_directory: ${method_dir}" | tee -a "${log}"
    echo "Output_directory: ${outdir}" | tee -a "${log}"

    echo "Processing ${cell} ..." | tee -a "${overall_log}"

    method_spliced="${method_dir}/${cell}_mRNA_spliced_final.sorted.bam"
    method_unspliced="${method_dir}/${cell}_pre_mRNA_unspliced.sorted.bam"
    method_ambiguous="${method_dir}/${cell}_isoform_unspliced.sorted.bam"

    missing=0
    for f in \
        "${method_spliced}" \
        "${method_unspliced}" \
        "${method_ambiguous}"
    do
        if [[ ! -f "${f}" ]]; then
            echo "Error: file not found: ${f}" | tee -a "${log}" | tee -a "${overall_log}"
            missing=1
        fi
    done

    if [[ "${missing}" -eq 1 ]]; then
        echo "Skipping ${cell} due to missing files." | tee -a "${log}" | tee -a "${overall_log}"
        continue
    fi

    echo "All required files found for ${cell}." | tee -a "${log}"

    run_fc "${method_spliced}"   "${outdir}" "${cell}_method_spliced"   "${log}"
    run_fc "${method_unspliced}" "${outdir}" "${cell}_method_unspliced" "${log}"
    run_fc "${method_ambiguous}" "${outdir}" "${cell}_method_ambiguous" "${log}"

    echo "Finished ${cell}" | tee -a "${log}" | tee -a "${overall_log}"
done

echo "All featureCounts jobs finished." | tee -a "${overall_log}"